version: "3"
services:
  # アプリケーションサーバー
  app:
    container_name: laravelApp_app
    build:
      context: ./build/prod/app
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
# ウェブサーバー
  nginx:
    container_name: laravelApp_nginx
    build:
      context: ./build/prod/nginx
      dockerfile: Dockerfile
    volumes:
      - ./build/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - app
