version: "3"
services:
  # アプリケーションサーバー
  backend:
    container_name: laravelApp_backend
    build:
      context: ./build/prod/backend
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
  # frontend:
  #   container_name: laravelApp_frontend
  #   build:
  #     context: ./build/prod/frontend
  #     dockerfile: Dockerfile

# ウェブサーバー
  nginx:
    container_name: laravelApp_nginx
    build:
      context: ./build/prod/nginx
      dockerfile: Dockerfile
    volumes:
      - ./build/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - backend
